### PR TITLE
Credit usage explanations

### PR DESCRIPTION
**Pull request by jdries**
This pull request adds initial documentation on job credit usage and estimation.

Needs further elaboration, but we want to cover a few of these aspects for SRR3/LPS.

### CODE REVIEW

**Review by handeerdem — COMMENTED** [review]
HI @jdries , I wonder if you should incorporate the "added-value" cost into your example, since it can be a significant amount.

**Comment by jdries** [comment]
I left out added value for now, because with what is exposed today in openEO platform, users should not encounter this, or do they?

**Review by m-mohr — APPROVED** [review]
I've fixed minor (formatting) issues and added the page to the menu.
Haven't checked the content as I'm not involved there.
Approval from the technical side of things.

**Comment by jdries** [comment]
I'm going to merge this one to have it online before the deadline. People have been notified, and we can always update afterwards.

**Comment by bschumac** [comment]
Thanks @jdries for uploading. We confirm this document for now.

**Pull request merged**
